views.row.google_news_fields:
  type: mapping
  label: 'Google news fields'
  mapping:
    loc_field:
      type: string
      label: 'Loc field'
    news_publication_name_field:
      type: label
      label: 'News publication name field'
    news_publication_language_field:
      type: string
      label: 'News publication language field'
    news_access_field:
      type: string
      label: 'News access field'
    news_genres_field:
      type: label
      label: 'News genres field'
    news_publication_date_field:
      type: string
      label: 'News publication date field'
    news_title_field:
      type: string
      label: 'News title field'
    news_keywords_field:
      type: string
      label: 'News keywords field'
    news_stock_tickers_field:
      type: label
      label: 'News stock tickers field'
    documentation:
      type: label
      label: 'Documentation'
